version: "3.9"

services:
  app:
    image: new:1
    ports:
      - "8000:8000"
    depends_on:
     - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./libshop-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lib
      - POSTGRES_USER=lib
      - POSTGRES_PASSWORD=123@456